AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dragons_api

  Sample SAM Template for dragons_api

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Tracing: Active
  Api:
    TracingEnabled: true

Resources:
  DragonTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "dragons"
      AttributeDefinitions:
        - AttributeName: "dragon_id"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "dragon_id"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      UserPoolName: DragonUserPool
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: "preferred_username"
          Required: true
          Mutable: true
        - AttributeDataType: String
          Name: "email"
          Required: true
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireLowercase: true
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: true

  UserPoolTokenClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: DragonsUserPoolClient
      GenerateSecret: false # Boolean to specify whether you want to generate a secret for the user pool client being created.
      SupportedIdentityProviders:
        - COGNITO
      CallbackURLs:
        - https://example.com/callback
      LogoutURLs:
        - https://example.com/signout
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - phone
        - aws.cognito.signin.user.admin

  DragonUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: dragon-domain
      UserPoolId:  !Ref UserPool

  DragonApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: DragonApi
      StageName: Prod
      # This is only needed if you are Requesting from a domain that is not shared with this API Domain
      # Know the security implications before doing this on a production site
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
      Auth:
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt "UserPool.Arn"

  DragonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dragons_api/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: url
          TABLE_NAME: dragons
          AWS_SAM_LOCAL: 0

      Events:
        ListDragons:
          Type: Api
          Properties:
            RestApiId: !Ref DragonApi
            Path: /dragons
            Method: get

        CreateDragon:
          Type: Api
          Properties:
            RestApiId: !Ref DragonApi
            Auth:
              Authorizer: CognitoAuthorizer
            Path: /dragons
            Method: post

      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DragonTable

Outputs:
  DragonFunction:
    Description: "Dragon Lambda Function ARN"
    Value: !GetAtt DragonFunction.Arn
  DragonFunctionIamRole:
    Description: "Implicit IAM Role created for Dragon function"
    Value: !GetAtt DragonFunctionRole.Arn
